services:
  db:
    image: postgres
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - /home/docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: restaurant-order
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      TZ: America/Mexico_City
